/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nanotech.validacionsatcfdi.GUI;

import com.nanotech.validacionsatcfdi.clases.CFDI;
import com.nanotech.validacionsatcfdi.clases.CFDIxml;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author nano
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void consultarPorParametros(){
        
        CFDI objCfdi = new CFDI();
        objCfdi.setRFCemisor(txtRFCEmisor.getText());
        objCfdi.setRFCreceptor(txtRFCReceptor.getText());
        objCfdi.setMonto(txtMonto.getValue().toString());
        objCfdi.setUUID(txtUUID1.getValue() + "-" + txtUUID2.getValue() + "-" + 
                        txtUUID3.getValue() + "-" + txtUUID4.getValue().toString() + "-" + txtUUID5.getValue().toString());
        
        
        switch(objCfdi.getExiste()){
            
            case "N - 602: Comprobante no encontrado.":
                
                lblResultado.setText("El CFDI no se pudo localizar");
                
                break;
               
            case "S - Comprobante obtenido satisfactoriamente.":
                
                lblResultado.setText("CFDI encontrado satisfactoriamente \n" +"Su Estado es: " + objCfdi.getEstatus());
                
                break;
                
            case "N - 601: La expresión impresa proporcionada no es válida.":
                
                lblResultado.setText("Los datos ingresados no son válidos");
                
                break;
                
            default:
                
                lblResultado.setText("Error al consultar el CFDI");
                
                break;
            
        }
        
    }
    
    public void limpiarCampos(){
        
        txtMonto.setValue(0);
        txtRFCEmisor.setText("");
        txtRFCReceptor.setText("");
        txtRuta.setText("");
        txtUUID1.setValue("");
        txtUUID2.setValue("");
        txtUUID3.setValue("");
        txtUUID4.setValue("");
        txtUUID5.setValue("");
        
    }
    
    public void consultarPorXML(){
        
        CFDIxml objXML = new CFDIxml(txtRuta.getText());
        objXML.leerArchivoXML();
        
        CFDI objCfdi = new CFDI(objXML.getDatoRFCemisor(), objXML.getDatoRFCrecpetor(), objXML.getDatoMonto(), objXML.getDatoUUID());
        
        switch(objCfdi.getExiste()){
            
            case "N - 602: Comprobante no encontrado.":
                
                lblResultado.setText("El CFDI no se pudo localizar");
                
                break;
               
            case "S - Comprobante obtenido satisfactoriamente.":
                
                lblResultado.setText("CFDI encontrado satisfactoriamente \n" +"Su Estado es: " + objCfdi.getEstatus());
                
                break;
                
            case "N - 601: La expresión impresa proporcionada no es válida.":
                
                lblResultado.setText("Los datos ingresados no son válidos");
                
                break;
                
            default:
                
                lblResultado.setText("Error al consultar el CFDI");
                
                break;
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpOpciones = new javax.swing.JTabbedPane();
        jpDesdeArchivoXML = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnRuta = new javax.swing.JButton();
        txtRuta = new javax.swing.JTextField();
        jpDesdeDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUUID1 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUUID2 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUUID3 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtUUID4 = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtUUID5 = new javax.swing.JFormattedTextField();
        txtRFCEmisor = new javax.swing.JTextField();
        txtRFCReceptor = new javax.swing.JTextField();
        jpResultados = new javax.swing.JPanel();
        lblResultado = new javax.swing.JLabel();
        jpBotones = new javax.swing.JPanel();
        btnValidar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuOpciones = new javax.swing.JMenu();
        mnuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Validar estatus de CFDI");
        setResizable(false);

        jtpOpciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jpDesdeArchivoXML.setBackground(new java.awt.Color(2, 13, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ruta de Archivo XML:");

        btnRuta.setBackground(new java.awt.Color(231, 96, 18));
        btnRuta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRuta.setForeground(new java.awt.Color(255, 255, 255));
        btnRuta.setText("...");
        btnRuta.setBorder(null);
        btnRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaActionPerformed(evt);
            }
        });

        txtRuta.setEditable(false);
        txtRuta.setBackground(new java.awt.Color(255, 255, 255));
        txtRuta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtRuta.setBorder(null);

        javax.swing.GroupLayout jpDesdeArchivoXMLLayout = new javax.swing.GroupLayout(jpDesdeArchivoXML);
        jpDesdeArchivoXML.setLayout(jpDesdeArchivoXMLLayout);
        jpDesdeArchivoXMLLayout.setHorizontalGroup(
            jpDesdeArchivoXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDesdeArchivoXMLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDesdeArchivoXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDesdeArchivoXMLLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpDesdeArchivoXMLLayout.createSequentialGroup()
                        .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRuta, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpDesdeArchivoXMLLayout.setVerticalGroup(
            jpDesdeArchivoXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDesdeArchivoXMLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDesdeArchivoXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jtpOpciones.addTab("Archivo XML", jpDesdeArchivoXML);

        jpDesdeDatos.setBackground(new java.awt.Color(2, 13, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RFC Emisor:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RFC Receptor:");

        txtMonto.setBackground(new java.awt.Color(255, 255, 255));
        txtMonto.setBorder(null);
        txtMonto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.0##"))));
        txtMonto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Monto:");

        txtUUID1.setBackground(new java.awt.Color(255, 255, 255));
        txtUUID1.setBorder(null);
        try {
            txtUUID1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AAAAAAAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtUUID1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("UUID:");

        jLabel5.setText("-");

        txtUUID2.setBackground(new java.awt.Color(255, 255, 255));
        txtUUID2.setBorder(null);
        try {
            txtUUID2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AAAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtUUID2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setText("-");

        txtUUID3.setBackground(new java.awt.Color(255, 255, 255));
        txtUUID3.setBorder(null);
        try {
            txtUUID3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AAAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtUUID3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setText("-");

        txtUUID4.setBackground(new java.awt.Color(255, 255, 255));
        txtUUID4.setBorder(null);
        try {
            txtUUID4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AAAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtUUID4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setText("-");

        txtUUID5.setBackground(new java.awt.Color(255, 255, 255));
        txtUUID5.setBorder(null);
        try {
            txtUUID5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AAAAAAAAAAAA")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtUUID5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtRFCEmisor.setBackground(new java.awt.Color(255, 255, 255));
        txtRFCEmisor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRFCEmisor.setBorder(null);
        txtRFCEmisor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFCEmisorKeyTyped(evt);
            }
        });

        txtRFCReceptor.setBackground(new java.awt.Color(255, 255, 255));
        txtRFCReceptor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtRFCReceptor.setBorder(null);
        txtRFCReceptor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRFCReceptorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jpDesdeDatosLayout = new javax.swing.GroupLayout(jpDesdeDatos);
        jpDesdeDatos.setLayout(jpDesdeDatosLayout);
        jpDesdeDatosLayout.setHorizontalGroup(
            jpDesdeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDesdeDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDesdeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDesdeDatosLayout.createSequentialGroup()
                        .addComponent(txtUUID1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUUID2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUUID3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUUID4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUUID5, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                    .addGroup(jpDesdeDatosLayout.createSequentialGroup()
                        .addGroup(jpDesdeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDesdeDatosLayout.createSequentialGroup()
                                .addGroup(jpDesdeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpDesdeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRFCEmisor)
                                    .addComponent(txtRFCReceptor, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)))
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpDesdeDatosLayout.setVerticalGroup(
            jpDesdeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDesdeDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDesdeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRFCEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDesdeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRFCReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDesdeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDesdeDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUUID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtUUID2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtUUID3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtUUID4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtUUID5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpOpciones.addTab("Datos ", jpDesdeDatos);

        jpResultados.setBackground(new java.awt.Color(204, 204, 204));

        lblResultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpResultadosLayout = new javax.swing.GroupLayout(jpResultados);
        jpResultados.setLayout(jpResultadosLayout);
        jpResultadosLayout.setHorizontalGroup(
            jpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpResultadosLayout.setVerticalGroup(
            jpResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpResultadosLayout.createSequentialGroup()
                .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpBotones.setBackground(new java.awt.Color(2, 13, 30));

        btnValidar.setBackground(new java.awt.Color(231, 96, 18));
        btnValidar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnValidar.setForeground(new java.awt.Color(255, 255, 255));
        btnValidar.setText("Validar Estatus de XML");
        btnValidar.setBorder(null);
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        btnnuevo.setBackground(new java.awt.Color(231, 96, 18));
        btnnuevo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnnuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnnuevo.setText("Nueva Búsqueda");
        btnnuevo.setBorder(null);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotonesLayout = new javax.swing.GroupLayout(jpBotones);
        jpBotones.setLayout(jpBotonesLayout);
        jpBotonesLayout.setHorizontalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpBotonesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnValidar, btnnuevo});

        jpBotonesLayout.setVerticalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnValidar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mnuOpciones.setText("Opciones");
        mnuOpciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(mnuOpciones);

        mnuAyuda.setText("Ayuda");
        mnuAyuda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtpOpciones)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jtpOpciones)
                .addGap(0, 0, 0)
                .addComponent(jpResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        
                
        if(jtpOpciones.getSelectedIndex() != 0){
            
            if(txtRFCEmisor.getText().isEmpty() || txtRFCReceptor.getText().isEmpty() && txtMonto.getValue().toString().isEmpty() ||
                txtUUID1.getValue().toString().isEmpty() || txtUUID2.getValue().toString().isEmpty() || txtUUID3.getValue().toString().isEmpty() ||
                txtUUID4.getValue().toString().isEmpty() || txtUUID5.getValue().toString().isEmpty()){
            
                JOptionPane.showMessageDialog(this, "Se deben llenar todos los campos", "Mensaje - Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            
        }
            
            consultarPorParametros();
            return;
            
        }
        
        if(txtRuta.getText().isEmpty()){ JOptionPane.showMessageDialog(this, "Selecciona un Archivo para procesar", "Mensaje - Advertencia", JOptionPane.WARNING_MESSAGE); return;}
        
        consultarPorXML();
        
    }//GEN-LAST:event_btnValidarActionPerformed

    private void txtRFCEmisorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFCEmisorKeyTyped
        
        if(txtRFCEmisor.getText().length() == 13){
            
            evt.consume();
            
        }
        
    }//GEN-LAST:event_txtRFCEmisorKeyTyped

    private void txtRFCReceptorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRFCReceptorKeyTyped
        
        if(txtRFCReceptor.getText().length() == 13){
            
            evt.consume();
            
        }
        
    }//GEN-LAST:event_txtRFCReceptorKeyTyped

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        
        limpiarCampos();
        
        btnRuta.requestFocus();
        
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaActionPerformed
        
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos XML", "xml");
        JFileChooser abrirArchivo = new JFileChooser();
        abrirArchivo.setFileFilter(filtro);
        abrirArchivo.setDialogTitle("Escoge el XML de un CFDI");
                
        int opcion = abrirArchivo.showOpenDialog(this);
        
        if(opcion == JFileChooser.APPROVE_OPTION){
            
            txtRuta.setText(abrirArchivo.getSelectedFile().getPath());
            
        }
        
    }//GEN-LAST:event_btnRutaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRuta;
    private javax.swing.JButton btnValidar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jpBotones;
    private javax.swing.JPanel jpDesdeArchivoXML;
    private javax.swing.JPanel jpDesdeDatos;
    private javax.swing.JPanel jpResultados;
    private javax.swing.JTabbedPane jtpOpciones;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JFormattedTextField txtMonto;
    private javax.swing.JTextField txtRFCEmisor;
    private javax.swing.JTextField txtRFCReceptor;
    private javax.swing.JTextField txtRuta;
    private javax.swing.JFormattedTextField txtUUID1;
    private javax.swing.JFormattedTextField txtUUID2;
    private javax.swing.JFormattedTextField txtUUID3;
    private javax.swing.JFormattedTextField txtUUID4;
    private javax.swing.JFormattedTextField txtUUID5;
    // End of variables declaration//GEN-END:variables
}
